# Ansible managed. Don't change this file manually. Template info: /vendor/collections/ansible_collections/ethpandaops/general/roles/generate_kubernetes_config/templates/dora-endpoints-cl.yaml.j2
# Consensus layer endpoints

- url: https://bn-bootnode-1.srv.frames-devnet-0.ethpandaops.io
  name: bootnode-1
  authGroup: pandaops
  priority: -1
- url: https://bn-lighthouse-ethrex-1.srv.frames-devnet-0.ethpandaops.io
  name: lighthouse-ethrex-1
  authGroup: pandaops
  priority: -1
  archive: true
- url: https://bn-lighthouse-geth-1.srv.frames-devnet-0.ethpandaops.io
  name: lighthouse-geth-1
  authGroup: pandaops
  priority: -1
  archive: true
- url: https://bn-lighthouse-geth-2.srv.frames-devnet-0.ethpandaops.io
  name: lighthouse-geth-2
  authGroup: pandaops
  priority: -1
  archive: true
- url: https://bn-lighthouse-nethermind-1.srv.frames-devnet-0.ethpandaops.io
  name: lighthouse-nethermind-1
  authGroup: pandaops
  priority: -1
  archive: true
- url: https://bn-lighthouse-nethermind-2.srv.frames-devnet-0.ethpandaops.io
  name: lighthouse-nethermind-2
  authGroup: pandaops
  priority: -1
  archive: true
- url: https://bn-lighthouse-reth-1.srv.frames-devnet-0.ethpandaops.io
  name: lighthouse-reth-1
  authGroup: pandaops
  priority: -1
  archive: true
- url: https://bn-lighthouse-reth-2.srv.frames-devnet-0.ethpandaops.io
  name: lighthouse-reth-2
  authGroup: pandaops
  priority: -1
  archive: true

