# Ansible managed. Don't change this file manually. Template info: /vendor/collections/ansible_collections/ethpandaops/general/roles/generate_kubernetes_config/templates/testnet-homepage.yaml.j2

testnet-homepage:
  fullnameOverride: homepage

  replicas: 1

  image:
    repository: ethpandaops/ethereum-testnet-homepage
    tag: latest
    pullPolicy: Always
  resources:
    requests:
      cpu: 33m
      memory: 64Mi
  ingress:
    enabled: true

    className: ingress-nginx-public
    annotations:
      nginx.ingress.kubernetes.io/proxy-body-size: "0"
      nginx.ingress.kubernetes.io/configuration-snippet: |
        sub_filter '</head>' '<script src="https://pandamenu.ethpandaops.io/panda-menu-1.0.1.js" integrity="sha384-icGX6g6CzB0tqlhDc6Su4c6IPVbcbUvfM3xjbbFYsYBwuZR79WkmOxDhGEPfmyn2" crossorigin="anonymous"></script></head>';
        sub_filter_types text/html;
        sub_filter_once off;

    hosts:
      - host: frames-devnet-0.ethpandaops.io
        paths:
          - path: /
            pathType: Prefix

  customMarkdown: |-
    ## Network Spec
    https://notes.ethereum.org/@ethpandaops/frames-devnet-0

    ## Ansible setup
    https://github.com/ethpandaops/frames-devnets

    ## Client versions
    https://github.com/ethpandaops/frames-devnets/blob/master/ansible/inventories/devnet-0/group_vars/all/images.yaml

    ## Validator ranges
    - https://config.frames-devnet-0.ethpandaops.io/api/v1/nodes/validator-ranges

    Some examples:
    ```sh
    ## Pretty print in YAML format
    curl -s https://config.frames-devnet-0.ethpandaops.io/api/v1/nodes/validator-ranges \
      | yq '.ranges' -P
    ```

    ## Ethereum node inventory
    - https://config.frames-devnet-0.ethpandaops.io/api/v1/nodes/inventory

    Some examples on how to filter specific data from the node inventory:
    ```sh
    # Getting execution layer client enodes
    curl -s https://config.frames-devnet-0.ethpandaops.io/api/v1/nodes/inventory \
      | jq -r '.ethereum_pairs[] | .execution.enode'
    # Getting conseus layer client ENRs
    curl -s https://config.frames-devnet-0.ethpandaops.io/api/v1/nodes/inventory \
      | jq -r '.ethereum_pairs[] | .consensus.enr'
    ```

    ## Genesis configuration
    ### Execution layer clients
    - https://config.frames-devnet-0.ethpandaops.io/el/genesis.json
    - https://config.frames-devnet-0.ethpandaops.io/el/besu.json
    - https://config.frames-devnet-0.ethpandaops.io/el/chainspec.json

    ### Consensus layer clients
    - https://config.frames-devnet-0.ethpandaops.io/cl/config.yaml
    - https://config.frames-devnet-0.ethpandaops.io/cl/genesis.ssz
    - https://config.frames-devnet-0.ethpandaops.io/cl/deposit_contract.txt
    - https://config.frames-devnet-0.ethpandaops.io/cl/deposit_contract_block.txt
    - https://config.frames-devnet-0.ethpandaops.io/cl/deposit_contract_block_hash.txt


  customArgs:
    - -b
    - https://frames-devnet-0.ethpandaops.io

  config:
    baseURL: https://frames-devnet-0.ethpandaops.io
    languageCode: en-us
    title: "frames-devnet-0"
    theme: PaperMod
    markup:
      highlight:
        codeFences: true
        guessSyntax: true
        lineNos: false
        style: monokai
    params:
      disableThemeToggle: true
      defaultTheme: dark
      ethereum:
        faucetUrl: https://faucet.frames-devnet-0.ethpandaops.io
        rpcUrl: https://rpc.frames-devnet-0.ethpandaops.io
        beaconRpcUrl: https://beacon.frames-devnet-0.ethpandaops.io
        forkmonUrl: https://forkmon.frames-devnet-0.ethpandaops.io
        assertoorUrl: https://assertoor.frames-devnet-0.ethpandaops.io
        beaconexplorerUrl: "https://frames-devnet-0.beaconcha.in"
        doraUrl: https://dora.frames-devnet-0.ethpandaops.io
        checkpointSyncUrl: "https://checkpoint-sync.frames-devnet-0.ethpandaops.io"
        blobscanUrl: https://blobscan.com
        blobscanethpandaUrl: https://blobscan.frames-devnet-0.ethpandaops.io
        ethstatsUrl: https://ethstats.frames-devnet-0.ethpandaops.io
        chainName: "frames-devnet-0"
        chainId: "7034189865"
        github: https://github.com/ethpandaops/frames-devnets/tree/master/network-configs/devnet-0/metadata
        syncoorUrl: https://syncoor.frames-devnet-0.ethpandaops.io
      metamask:
        enabled: true
      logo:
        enabled: false
        url: https://i.imgur.com/M0gEdpw.png
      assets:
        favicon: https://i.imgur.com/M0gEdpw.png
        favicon16x16: https://i.imgur.com/M0gEdpw.png
        favicon32x32: https://i.imgur.com/M0gEdpw.png
        apple_touch_icon: https://i.imgur.com/M0gEdpw.png
        safari_pinned_tab: https://i.imgur.com/M0gEdpw.png

      links:
      - name: "Devnet Spec"
        dataLookup: github
      - name: "JSON RPC"
        dataLookup: rpcUrl
      - name: "Beacon RPC"
        dataLookup: beaconRpcUrl
      - name: "Dora the Explorer"
        dataLookup: doraUrl
      - name: "Syncoor"
        dataLookup: syncoorUrl
      - name: "Assertoor"
        dataLookup: assertoorUrl
      - name: "Checkpoint Sync"
        dataLookup: checkpointSyncUrl
      - name: "Faucet"
        dataLookup: faucetUrl
      - name: "Forkmon"
        dataLookup: forkmonUrl
    menu:
      main:
        - identifier: ethereum-website
          name: ethereum.org
          url: https://ethereum.org
          weight: 30
    disableKinds: ["taxonomy", "taxonomyTerm"]
    copyright: "Long live the surge"
